version: "3.9"

services:
  db:
    image: postgres:latest
    restart: always
    container_name: band_spotter
    environment:
      POSTGRES_DB: band_spotter
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - postgres:/data/postgres
    networks:
      - caxinhas

volumes:
  postgres:


networks:
  caxinhas:
    driver: bridge